ArjunSharda/Searchor

examples/searchamazon.py
examples/searchbing.py
examples/searchduckduckgo.py
examples/searchgoogle.py
examples/searchwikipedia.py
examples/searchyahoo.py

Add examples

---

Code/CHANGELOG.txt
Code/Searchor/__init__.py
Code/setup.py

Add GitHub search queries function

---

Code/Searchor/__init__.py

Hey,
I added, as the Title says, some extra search functions.
List of all new:
Target: https://target.com
Genius: https://genius.com
Twitch: https://twitch.tv
StackOverflow: https://stackoverflow.com

Added: Target, Genius, Twitch and StackOverflow to the search functions.

---

Code/Searchor/__init__.py

Since many people search for the latest lingo or the buzz word or that obscure term that no one really know the definition for and can't seem to find it in a dictionary

Including Urban Dictionary

---

Code/Searchor/__init__.py

Hey, 
I added some new Websites.
List of all new:
Reddit (https://www.reddit.com/)
Lenovo (https://www.lenovo.com/us/en/)
InstantGaming (https://www.instant-gaming.com/en/)
Textures (https://www.textures.com/)
Crunchyroll (https://beta.crunchyroll.com/). see comment.

New Websites.

---

README.md
src/searchor/__init__.py

some widely used engines added

added view engine list function 

---

PULL_REQUEST_TEMPLATE.md

Closes #37 
Do tell me if there is anything you want me to change or add.

added pull request template 

---

LEARN.md

- Changed wording
- Fixed some typos
The Learn.MD file
No

Update Learn.MD wording

---

src/searchor/__init__.py

This PR adds the FedEx search queries function regarding #55.
This PR affects the [src/searchor/\_\_init\_\_.py](https://github.com/ArjunSharda/Searchor/compare/ArjunSharda:Searchor:main...huyszn:Searchor:fedex) file.
The search query is based on the en-US version of the FedEx site.

Added FedEx search queries function

---

src/searchor/__init__.py

This pull request is about adding the G2 search queries function.
I have added the G2 search queries function in src/_init_.py
See if I make any mistakes or any else I have to do; please let me know as I am a beginner.

G2 search queries function added

---

README.md
src/searchor/__init__.py

added ups search query, mentioned in issue #61 
will affect __init__.py file. 
---

added ups query 

---

README.md
src/searchor/__init__.py

Added instructions to both users and contributors in readme file and init file 
will affect readme file and init file

added instructions

---

src/searchor/__init__.py

- Adds medium search query
- closes #64

Added medium search query

---

README.md

Adds changelog for v2.1.2
Adds changelog for v2.1.2
**NOTE FOR HACKTOBERFEST**
All submissions through October 1 - October 31 will be counting in this repository.
N/A

Add changelog for v2.1.2

---

src/searchor/__init__.py

- Adds spotify search query
- closes #70

added Spotify search function

---

src/searchor/__init__.py

Add Reddit Search

---

src/searchor/__init__.py

Fixes #76 and changes the link for AOL due to it being a UK link and so I made it for global use
The __init__.py file
No

Add AWS search + change link for AOL

---

CODE_OF_CONDUCT.md

Changing the word "software team leader" to "collaborator". It seems more better as there is a collaboration team for Searchor.
The code of conduct

docs(CODE_OF_CONDUCT.md) Change software team leader to "collaborator"

---

examples/custom.py
examples/searchamazon.py
examples/searchbing.py
examples/searchduckduckgo.py
examples/searchgoogle.py
examples/searchwikipedia.py
examples/searchyahoo.py
src/searchor/__init__.py

- removed duplicate Amazon and AOL
- code formatting
- added blogspot search query
- closes #79

Added BlogSpot Search query

---

README.md

- Adds a discord button to the README.md
The README.md
No

Add discord button to README.md

---

src/searchor/__init__.py

Added GitLab search query
Closes #89

Added GitLab search query

---

src/searchor/__init__.py

Added three search engines - Brave, Instagram, AlternativeTo
https://search.brave.com/
https://alternativeto.net/
https://instagram.com/

added instagram, brave and alternativeto search engines

---

src/searchor/__init__.py

To add search engine query for Docker Hub 
useful in DevOps
will show the respective or required registry for containerization

#95 Added Docker Hub search Query Engine

---

src/searchor/__init__.py

I have added unsplash search engine

Added unsplash search engine

---

src/searchor/__init__.py

- Add google maps and images query
related to #88

Add google maps and images query

---

NOTICE.md
examples/copy_url.py
src/searchor/__init__.py

This PR adds a feature using which the generated url gets copied to clipboard. This feature is optional.
This PR will affect the file `./src/__init__.py`
This PR will add a file `./examples/copy_url.py`

Copy URL to clipboard

---

README.md

- PR is related to the  #107.
- Added Contributors and made readme more appealing
- The new Contributing will have better view about the project
- The contributors would be acknowledged after there PR's are merged by mention them in README file
- The Contributors list is automatically updated
- Added Copyright Logo in README file

Contributors Section and Socalify added

---

src/searchor/__init__.py

added hoogle a search engine for haskell related searches added naver a search south korean search engine
added CC a lisence search engine

added extra search engines

---

README.md
src/searchor/__init__.py

added reuters search query

---

examples/cli/SUPPORTED_OPTIONS.md

Made examples in  `SUPPORTED_OPTIONS.md` more clear 
File : `SUPPORTED_OPTIONS.md`

Fixed unclear example in SUPPORTED_OPTIONS.md

---

.github/ISSUE_TEMPLATE/bug_report.md

Corrected comments in `bug_report.md`
It will affect the file `bug_report.md`.

Fixed comments in bug_report.md

---

.dockerignore
Dockerfile
requirements.txt

Dockerfile created to build and test `searchor`.
FIles `Dockerfile`, `.dockerignore` and `requirements.txt` have been added.
README.md can be modified and the following line can be added.
```Docker
sudo docker built -t searchor .
```

Introduce docker 

---

README.md

Add following procedures about docker to README.md
- Building the docker image
- Running searchor on the docker container
Update README.md
There was a plan to update README.md in #134, but it seems to be missing.

Add about docker to README.md

---

src/searchor/__init__.py

Importing only  specific module ie. `copy` from `pyperclip` 
File `/src/__init__.py` has been changed

Import only `copy` from `pyperclip`

---

examples/cli/SUPPORTED_OPTIONS.md

Grammar mistake rectified
Minor grammar edit.
CLI examples page

Minor edit

---

README.md
setup.py
src/searchor/__init__.py

adds v2.5.0 updates
fixes #145 
init py

v2.5.0 Pre-Release
